### ISSUE TITLE
ADB not working

### ISSUE THREAD

**Issue by markdegrootnl** [GS290-dev/android_device_gigaset_GX290-unified#1]
I can't seem to get ADB working on the GX290 with Lineage 19.1. 

When I turn on USB Debugging, I see the device disconnecting in `dmesg` but is does not reconnect. `adb devices` does not show the device either. When I disable USB Debugging, the device reconnects in `dmesg` using whatever USB mode I've selected in the settings.

ADB is working normally in the Stock firmware and also in [/e/os](https://community.e.foundation/t/gigaset-gx290-plus/34260/35) but I want to use Lineage.

Any idea how I can investigate and/or solve this?

**Comment by nift4** [comment]
1. Did you try to reboot?
2. Are you rooted? If so, what mods? And can you use some root LogCat app to catch a log?
3. What build version? If prebuilt, where did you download it? If self-built, what date?

**Comment by markdegrootnl** [comment]
1. Yes
2. Not rooted, but it is the `userdebug` build so `adb root` should be available, if ADB was working... I'll have a look at a LogCat app
3. Self built, yesterday using `repo init -u https://github.com/LineageOS/android.git -b lineage-19.1` and the manifest from https://github.com/GS290-dev/local_manifests/blob/main/gs290.xml. No further changes.

**Comment by markdegrootnl** [comment]
I juist built a lineage 18.1 image, and ADB is working with that one.
Edit: The /e/os version I tested with was also based on Android 11.

**Comment by nift4** [comment]
This is weird - it's fine on my GS290-compatible device on Android 12, and nothing really changed from Android 11 to 12 on the individual device trees. I will look into it, thanks for the report.

**Comment by markdegrootnl** [comment]
Let me know if I can do anything to help

**Comment by nift4** [comment]
Does wireless ADB feature work?

**Comment by markdegrootnl** [comment]
Wireless ADB also does not work. I can enable it in the settings, but does not work.
- Paring with pairing code does show a code, but no IP address and port.
- Pairing with QR code, scans the code but keeps "Pairing device..."

**Comment by markdegrootnl** [comment]
I've just built LineageOS 19.1 for the G**S**290 and ADB works. Any idea what the difference is between the 2 devices and why it's not working on my G**X**290?

**Comment by nift4** [comment]
I don't know, and honestly, I only ever tested Android 12 on the GS290, as I use the GX290 as daily driver. I did not expect it to be an GX290-only issue. I will try to move devices and reproduce the issue, thanks for the report.

**Comment by markdegrootnl** [comment]
Could there be a difference between a GX290 and GX290 Plus?

You're located in Germany right? Would it help if I sent you a GX290 Plus to figure this out?

**Comment by nift4** [comment]
I have GX290+ already, I do not have the non-plus variant actually

**Comment by nift4** [comment]
Sorry, correction, I have the GX290 PRO. I did not even know there was 3 variants lol

**Comment by nift4** [comment]
Either way I thank you for the offer, I will check if I can reproduce it on my device, if not, I'll happily take it :)

**Comment by markdegrootnl** [comment]
I've rebuilt the Lineage 19.1 firmware for the GX290, and now ADB seems to be working.

**Comment by nift4** [comment]
Ah well, issues magically fixing itself 😂 saves me some effort. Thanks for reporting back
